name: run main.py
on:
  schedule:
    - cron: "03 23 * * *" # runs at 21:15
jobs:
  explore-gitHub-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
      - name: Execute main.py
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_BEARER: ${{ secrets.TWITCH_BEARER }}
          TWITCH_USERNAME: ${{ secrets.TWITCH_USERNAME }}
        run: python main.py
      - name: Log execution
        run: echo "Execution of the task at 21:15"
